AppointmentScheduler/AppointmentScheduler/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from scheduler import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^appt/schedule/$', views.schedule_appt),
    url(r'^find/appt/$', views.search_appt),
    url(r'^admin/', admin.site.urls),
]

AppointmentScheduler/scheduler/urls.py
from django.conf.urls import url
from scheduler import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
]

AppointmentScheduler/scheduler/models.py
from django.db import models

# Create your models here.

class Appointment(models.Model):
    date = models.CharField(max_length=260)
    time = models.CharField(max_length=10)
    description = models.CharField(max_length=260)

AppointmentScheduler/scheduler/forms.py
from django import forms
from scheduler.models import Appointment

class NewApptForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = '__all__'

AppointmentScheduler/scheduler/views.py
from django.shortcuts import render
from scheduler.models import Appointment
from scheduler.forms import NewApptForm
from django.core import serializers
from django.http import HttpResponse
import json


# Create your views here.

def index(request):

    # appoint_list = Appointment.objects.filter(
    #         description__icontains = "D"
    #     )
    # appt_dict = {
    #     'appointment_records': appoint_list,
    # }

    return render(request,'scheduler/index.html')

def schedule_appt(request):
    if request.method == "POST":
        date = request.POST['date']
        time = request.POST['time']
        description = request.POST['description']

        Appointment.objects.create(
            date = date,
            time = time,
            description = description
        )

        return HttpResponse('')


def search_appt(request):
    if request.method == "GET":
        description = request.GET['description']

        appoint_list = Appointment.objects.filter(
            description__icontains = description
        )
        appt_dict = {
        'appointment_records': appoint_list,
        }

        data = serializers.serialize("json", appoint_list)
        return HttpResponse(data, content_type='application/json')

    # return HttpResponse(json.dumps(appt_dict))

AppointmentScheduler/templates/scheduler/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Python Appointment App</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
    <!-- Moment Js -->
    <script src="https://cdn.jsdelivr.net/momentjs/2.12.0/moment.min.js"></script>
    <!-- Styles -->
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">

</head>

<body>

    <div class="container">

        <div class="jumbotron text-center">
            <h1>Appointment Scheduler</h1>
            <p>Search for recent appointments or add new ones</p>
        </div>

        <div>

            <div id="appt-btns">
                <button class="btn btn-outline-secondary" id="add-appt">
                    New Appointment
                </button>
                <button class="btn btn-outline-success" id="add-btn">
                    Add
                </button>
                <button class="btn btn-outline-danger" id="cancel-btn">
                    Cancel
                </button>
            </div>

            <div id="appt-form">

                <form method="POST">{% csrf_token %}
                    <div class="form-group">
                        <label for="appt-date">Date (YYYY-MM-DD - ex: 1999-01-25)</label>
                        <input type="text" class="form-control" id="id_date">
                    </div>
                    <div class="form-group">
                        <label for="appt-time">Time (HH:MM - ex: 05:30)</label>
                        <input type="text" class="form-control" id="id_time">
                    </div>
                    <div class="form-group">
                        <label for="appt-description">
                            Description
                        </label>
                        <textarea type="text" class="form-control" id="id_description" rows="3"></textarea>
                    </div>

                </form>
            </div>
        </div>

        <hr>

        <div class="search-form">
            <form class="form-inline">{% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" id="search" placeholder="Enter description...">
                </div>
                <button type="submit" class="btn btn-outline-primary" id="search-btn">Search</button>
            </form>
        </div>

        <hr>

        <div class="container">
                <table class="table table-striped table-bordered text-center">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody id="appointments">

                    </tbody>
                </table>

        </div>

    </div>

    <!-- JavaScript -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static "js/app.js" %}"></script>

</body>

</html>